print("Enter Eight Numbers")
st = set()

num = int(input())
st.add(num)
num = int(input())
st.add(num)
num = int(input())
st.add(num)
num = int(input())
st.add(num)
num = int(input())
st.add(num)
num = int(input())
st.add(num)
num = int(input())
st.add(num)
num = int(input())
st.add(num)

print(st)